web:
    image: nginx
    ports:
        - "8080:80"
    volumes:
        - ./docker/conf/nginx:/etc/nginx/conf.d
        - ./src:/srv/www
    links:
        - php

php:
    image: lchski/php:7-base-dev
    volumes:
        - ./src:/srv/www
    links:
        - db
    environment:
        XDEBUG_CONFIG: remote_host=10.10.10.10

db:
    image: mariadb
    volumes:
        - ./docker/data/db:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=dockerdev
        - MYSQL_USER=dockerdevuser
        - MYSQL_PASSWORD=password
